# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:			pretty
markdown:    		kramdown
# relative_permalinks: true

# Setup
title:				Swen Voigt
#tagline:			'A Jekyll theme'
description:		'' # hier steht der Text für die Sidebar... Brauche ich nicht. Sihe sidebar.html
#url:                'https://swenvoigt.github.io/swenvoigt/'
url:				'http://localhost:4000/'
baseurl:            ''
paginate:			5
excerpt_separator:	<!--more-->
encoding:			utf-8
banner-image:        /assets/img/mountain-cover.jpg


# About/contact
author:
  name:              Swen Voigt
  #url:               swenvoigt.github.io
  email:             swen.voigt@gmail.com

category_title_prefix: 'Beiträge in Kategorie '
category_dir:          'categories'

# Custom vars
version:             1.0.0

gems: [jekyll-paginate]

# cutomized / see _layouts/default.html, class: masthead-title
pages_list:       
  Über mich: '/about'
  Archiv: '/archive'


 
# Sitemap plugin:
sitemap:
   file: "/sitemap.xml"
   # exclude: "/atom.xml". "/feed.xml", "/feed/index.xml"
   # include_posts:	"/index.html"
   change_frequency_name: "change_frequency"
   priority_name: "priority"
    
  


